version: '3.4'

services:
  reviews-api:
    build:
      context: ./
      target: development
    ports:
      - 8888:8888
      - 10888:10888
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
  postgres:
    image: postgres:13.0-alpine
    volumes:
    - ./database_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=reviews
  redis:
    image: redis:6.0.8-alpine
    ports:
      - 6379:6379
